# Generated by Django 3.1.7 on 2021-03-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(max_length=750)),
                ('date', models.DateField(verbose_name='prize_date')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
