# Generated by Django 3.1.7 on 2021-04-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='file',
            field=models.FileField(upload_to='research/'),
        ),
    ]
