# Generated by Django 2.0.4 on 2021-06-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0004_auto_20210617_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='pdf_link',
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='abstract',
            field=models.URLField(default='None'),
        ),
    ]
