# Generated by Django 2.0.4 on 2021-06-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0005_auto_20210617_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='abstract',
            field=models.URLField(),
        ),
    ]
