# Generated by Django 2.0.4 on 2021-06-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0006_auto_20210617_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchpaper',
            old_name='abstract',
            new_name='abstract_pdf',
        ),
    ]
