# Generated by Django 3.0.3 on 2021-02-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sdid', models.CharField(default='sd00de01', max_length=8, primary_key=True, serialize=False)),
                ('usn', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('branch', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_photo/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_core', models.BooleanField(default=False)),
                ('core_position', models.CharField(choices=[('None', 'None'), ('SPM', 'Project Manager'), ('PM', 'Project Director'), ('MM', 'Mission Manager'), ('MD', 'Mission Director'), ('TM', 'Team Manager')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystem', models.CharField(choices=[('PL', 'Payload'), ('ADCS', 'ADCS'), ('EPS', 'Power'), ('ODHS', 'ODHS'), ('GC', 'Communication'), ('STR', 'Structure')], max_length=5)),
                ('position', models.CharField(choices=[('SSH', 'Subsystem Head'), ('CSE', 'Chief System Engineer'), ('SE', 'System Engineer'), ('SSE', 'Subsystem Engineer')], max_length=5)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.Student')),
            ],
        ),
        migrations.CreateModel(
            name='NonTechnical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('WEB', 'Website'), ('SPR', 'Public Relations and Sponsorship'), ('SM', 'Social Media'), ('DOC', 'Documentation'), ('FIN', 'Finance')], max_length=4)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.Student')),
            ],
        ),
    ]
