# Generated by Django 3.1.7 on 2021-03-31 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_photo/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystem', models.CharField(choices=[('PL', 'Payload'), ('ADCS', 'ADCS'), ('EPS', 'Power'), ('ODHS', 'ODHS'), ('GC', 'Communication'), ('STR', 'Structure')], max_length=5)),
                ('position', models.CharField(choices=[('SSH', 'Subsystem Head'), ('CSE', 'Chief System Engineer'), ('SE', 'System Engineer'), ('SSE', 'Subsystem Engineer')], max_length=5)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.student')),
            ],
        ),
        migrations.CreateModel(
            name='NonTechnical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('WEB', 'Website'), ('SPR', 'Public Relations and Sponsorship'), ('SM', 'Social Media'), ('DOC', 'Documentation'), ('FIN', 'Finance')], max_length=4)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.student')),
            ],
        ),
    ]
