# Generated by Django 3.1.7 on 2021-04-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_auto_20210403_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ETE', 'Electronics and Telecommunication Engineering'), ('ISE', 'Information Science and Engineering'), ('EIE', 'Electronics and Instrumentation Engineering'), ('EEE', 'Electronics and Electrical Engineering'), ('ML', 'Medical Electronics'), ('BT', 'BioTechnology'), ('MECH', 'Mechanical Engineering'), ('CV', 'Civil Engineering'), ('CHE', 'Chemical Engineering'), ('IEM', 'Industrial Engineering and Managment')], default='CSE', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='changethisemail@mailserver.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.URLField(default='changethislink.linkedin.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='core_position',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('SPM', 'Senior Project Manager'), ('PM', 'Project Manager'), ('MM', 'Mission Manager'), ('MD', 'Mission Director'), ('TM', 'Team Manager')], max_length=4, null=True),
        ),
    ]
