# Generated by Django 2.0.4 on 2021-05-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_auto_20210413_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='nontechnical',
            name='position',
            field=models.CharField(choices=[('H', 'Head'), ('SH', 'Sub Head')], default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('F', 'Founder'), ('C', 'Core Member'), ('TM', 'Technical Member'), ('NM', 'Nontechnical Member')], max_length=10, null=True),
        ),
    ]
