# Generated by Django 2.0.4 on 2021-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0004_auto_20210502_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nontechnical',
            name='position',
            field=models.CharField(choices=[('H', 'Head'), ('SH', 'Sub Head'), ('M', 'Member')], default='M', max_length=5),
        ),
    ]
