# Generated by Django 2.0.4 on 2021-06-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0008_auto_20210502_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nontechnical',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Members.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('F', 'Founder'), ('C', 'Core Member')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Members.Student'),
        ),
    ]
