# Generated by Django 2.0.4 on 2021-06-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0010_auto_20210603_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
