# Generated by Django 2.0.4 on 2021-06-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0011_auto_20210603_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical',
            name='subsystem',
            field=models.CharField(choices=[('PL', 'Payload'), ('ADCS', 'ADCS'), ('EPS', 'Power'), ('ODHS', 'ODHS'), ('GC', 'Communication'), ('STR', 'Structure and Thermal'), ('ROC', 'Rocketry')], max_length=5),
        ),
    ]
