# Generated by Django 2.0.4 on 2021-06-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0012_auto_20210603_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='core_position',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('SPM', 'Senior Project Manager'), ('PM', 'Project Manager'), ('MM', 'Mission Manager'), ('MD', 'Mission Director'), ('TM', 'Team Manager')], default='None', max_length=4, null=True),
        ),
    ]
