# Generated by Django 3.2.4 on 2021-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0015_auto_20210603_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nontechnical',
            name='position',
            field=models.CharField(choices=[('None', 'None'), ('H', 'Head'), ('SH', 'Sub Head'), ('M', 'Member')], default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='core_position',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('SPM', 'Senior Project Manager'), ('PM', 'Project Manager'), ('MM', 'Mission Manager'), ('MD', 'Mission Director'), ('TM', 'Team Manager'), ('RH', 'Rocketry Head'), ('NH', 'Non-Technical Head')], default='None', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='subsystem',
            field=models.CharField(choices=[('PL', 'Payload'), ('ADCS', 'ADCS'), ('EPS', 'Electrical Power System'), ('ODHS', 'ODHS'), ('GC', 'Communication'), ('STR', 'Structure and Thermal'), ('ROC', 'Rocketry')], max_length=5),
        ),
    ]
