# Generated by Django 3.2.4 on 2021-06-30 07:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0016_auto_20210623_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='technical',
            name='subsystem',
            field=models.CharField(choices=[('PL', 'Payload Subsystem'), ('ADCS', 'Attitude Determination and Control Subsystem'), ('EPS', 'Electrical Power System Subsystem'), ('ODHS', 'On Board Data Handling Susbsytem'), ('GC', 'Ground Control and Communication Subsystem'), ('STR', 'Structures and Thermal Susbsystem'), ('ROC', 'Rocketry')], max_length=5),
        ),
    ]
