# Generated by Django 3.2.4 on 2021-06-30 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0018_alter_faculty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical',
            name='subsystem',
            field=models.CharField(choices=[('PL', 'Payload Subsystem'), ('ADCS', 'Attitude Determination and Control Subsystem'), ('EPS', 'Electrical Power System Subsystem'), ('ODHS', 'On Board Data Handling Susbsytem'), ('GC', 'Ground Control and Communication Subsystem'), ('STR', 'Structures and Thermal Susbsystem')], max_length=5),
        ),
        migrations.CreateModel(
            name='Rocketry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocsystem', models.CharField(choices=[('AS', 'Aerodynamics and Structures'), ('GCS', 'Ground and Control System'), ('PS', 'Propulsion System')], max_length=5)),
                ('position', models.CharField(choices=[('None', 'None'), ('SSH', 'Subsystem Head'), ('CSE', 'Chief System Engineer'), ('SE', 'System Engineer'), ('SSE', 'Subsystem Engineer')], max_length=5)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Members.student')),
            ],
        ),
    ]
