# Generated by Django 3.2.4 on 2021-06-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0020_rename_rocsystem_rocketry_subsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocketry',
            name='subsystem',
            field=models.CharField(choices=[('AS', 'Aerodynamics and Structures'), ('GCS', 'Guidance and Control System'), ('PS', 'Propulsion System')], max_length=5),
        ),
    ]
