# Generated by Django 3.2.4 on 2021-07-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0021_alter_rocketry_subsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
